//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharedService.TaqehService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockTaqeh", Namespace="http://schemas.datacontract.org/2004/07/SharedLib")]
    [System.SerializableAttribute()]
    public partial class StockTaqeh : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ReserveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Taqeh TaqehField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaqehIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Reserve {
            get {
                return this.ReserveField;
            }
            set {
                if ((this.ReserveField.Equals(value) != true)) {
                    this.ReserveField = value;
                    this.RaisePropertyChanged("Reserve");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Taqeh Taqeh {
            get {
                return this.TaqehField;
            }
            set {
                if ((object.ReferenceEquals(this.TaqehField, value) != true)) {
                    this.TaqehField = value;
                    this.RaisePropertyChanged("Taqeh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaqehId {
            get {
                return this.TaqehIdField;
            }
            set {
                if ((this.TaqehIdField.Equals(value) != true)) {
                    this.TaqehIdField = value;
                    this.RaisePropertyChanged("TaqehId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Taqeh", Namespace="http://schemas.datacontract.org/2004/07/SharedLib")]
    [System.SerializableAttribute()]
    public partial class Taqeh : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Stuff AjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AjIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Stuff BackColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BackColorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Stuff BrightnessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BrightnessIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetLaminetStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetRecognizableNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte LTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Stuff ParcheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParcheIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Stuff ProducerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProducerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ThicknessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Stuff Aj {
            get {
                return this.AjField;
            }
            set {
                if ((object.ReferenceEquals(this.AjField, value) != true)) {
                    this.AjField = value;
                    this.RaisePropertyChanged("Aj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AjId {
            get {
                return this.AjIdField;
            }
            set {
                if ((this.AjIdField.Equals(value) != true)) {
                    this.AjIdField = value;
                    this.RaisePropertyChanged("AjId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Stuff BackColor {
            get {
                return this.BackColorField;
            }
            set {
                if ((object.ReferenceEquals(this.BackColorField, value) != true)) {
                    this.BackColorField = value;
                    this.RaisePropertyChanged("BackColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BackColorId {
            get {
                return this.BackColorIdField;
            }
            set {
                if ((this.BackColorIdField.Equals(value) != true)) {
                    this.BackColorIdField = value;
                    this.RaisePropertyChanged("BackColorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Stuff Brightness {
            get {
                return this.BrightnessField;
            }
            set {
                if ((object.ReferenceEquals(this.BrightnessField, value) != true)) {
                    this.BrightnessField = value;
                    this.RaisePropertyChanged("Brightness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrightnessId {
            get {
                return this.BrightnessIdField;
            }
            set {
                if ((this.BrightnessIdField.Equals(value) != true)) {
                    this.BrightnessIdField = value;
                    this.RaisePropertyChanged("BrightnessId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetLaminetStatus {
            get {
                return this.GetLaminetStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.GetLaminetStatusField, value) != true)) {
                    this.GetLaminetStatusField = value;
                    this.RaisePropertyChanged("GetLaminetStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetRecognizableName {
            get {
                return this.GetRecognizableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GetRecognizableNameField, value) != true)) {
                    this.GetRecognizableNameField = value;
                    this.RaisePropertyChanged("GetRecognizableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte LType {
            get {
                return this.LTypeField;
            }
            set {
                if ((this.LTypeField.Equals(value) != true)) {
                    this.LTypeField = value;
                    this.RaisePropertyChanged("LType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Stuff Parche {
            get {
                return this.ParcheField;
            }
            set {
                if ((object.ReferenceEquals(this.ParcheField, value) != true)) {
                    this.ParcheField = value;
                    this.RaisePropertyChanged("Parche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParcheId {
            get {
                return this.ParcheIdField;
            }
            set {
                if ((this.ParcheIdField.Equals(value) != true)) {
                    this.ParcheIdField = value;
                    this.RaisePropertyChanged("ParcheId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Stuff Producer {
            get {
                return this.ProducerField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerField, value) != true)) {
                    this.ProducerField = value;
                    this.RaisePropertyChanged("Producer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProducerId {
            get {
                return this.ProducerIdField;
            }
            set {
                if ((this.ProducerIdField.Equals(value) != true)) {
                    this.ProducerIdField = value;
                    this.RaisePropertyChanged("ProducerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Thickness {
            get {
                return this.ThicknessField;
            }
            set {
                if ((this.ThicknessField.Equals(value) != true)) {
                    this.ThicknessField = value;
                    this.RaisePropertyChanged("Thickness");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stuff", Namespace="http://schemas.datacontract.org/2004/07/SharedLib")]
    [System.SerializableAttribute()]
    public partial class Stuff : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BackColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrightnessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HardnessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParcheField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProducerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThicknessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string str1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string str2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string str3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aj {
            get {
                return this.AjField;
            }
            set {
                if ((object.ReferenceEquals(this.AjField, value) != true)) {
                    this.AjField = value;
                    this.RaisePropertyChanged("Aj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BackColor {
            get {
                return this.BackColorField;
            }
            set {
                if ((object.ReferenceEquals(this.BackColorField, value) != true)) {
                    this.BackColorField = value;
                    this.RaisePropertyChanged("BackColor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brightness {
            get {
                return this.BrightnessField;
            }
            set {
                if ((object.ReferenceEquals(this.BrightnessField, value) != true)) {
                    this.BrightnessField = value;
                    this.RaisePropertyChanged("Brightness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hardness {
            get {
                return this.HardnessField;
            }
            set {
                if ((object.ReferenceEquals(this.HardnessField, value) != true)) {
                    this.HardnessField = value;
                    this.RaisePropertyChanged("Hardness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parche {
            get {
                return this.ParcheField;
            }
            set {
                if ((object.ReferenceEquals(this.ParcheField, value) != true)) {
                    this.ParcheField = value;
                    this.RaisePropertyChanged("Parche");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Producer {
            get {
                return this.ProducerField;
            }
            set {
                if ((object.ReferenceEquals(this.ProducerField, value) != true)) {
                    this.ProducerField = value;
                    this.RaisePropertyChanged("Producer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Thickness {
            get {
                return this.ThicknessField;
            }
            set {
                if ((object.ReferenceEquals(this.ThicknessField, value) != true)) {
                    this.ThicknessField = value;
                    this.RaisePropertyChanged("Thickness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string str1 {
            get {
                return this.str1Field;
            }
            set {
                if ((object.ReferenceEquals(this.str1Field, value) != true)) {
                    this.str1Field = value;
                    this.RaisePropertyChanged("str1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string str2 {
            get {
                return this.str2Field;
            }
            set {
                if ((object.ReferenceEquals(this.str2Field, value) != true)) {
                    this.str2Field = value;
                    this.RaisePropertyChanged("str2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string str3 {
            get {
                return this.str3Field;
            }
            set {
                if ((object.ReferenceEquals(this.str3Field, value) != true)) {
                    this.str3Field = value;
                    this.RaisePropertyChanged("str3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DapperException", Namespace="http://schemas.datacontract.org/2004/07/SahraShoesService.Exceptions")]
    [System.SerializableAttribute()]
    public partial class DapperException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pofak", Namespace="http://schemas.datacontract.org/2004/07/SharedLib")]
    [System.SerializableAttribute()]
    public partial class Pofak : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Stuff ColorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ColorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetRecognizableNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float GlueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ThicknessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Stuff TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Stuff Color {
            get {
                return this.ColorField;
            }
            set {
                if ((object.ReferenceEquals(this.ColorField, value) != true)) {
                    this.ColorField = value;
                    this.RaisePropertyChanged("Color");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ColorId {
            get {
                return this.ColorIdField;
            }
            set {
                if ((this.ColorIdField.Equals(value) != true)) {
                    this.ColorIdField = value;
                    this.RaisePropertyChanged("ColorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetRecognizableName {
            get {
                return this.GetRecognizableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GetRecognizableNameField, value) != true)) {
                    this.GetRecognizableNameField = value;
                    this.RaisePropertyChanged("GetRecognizableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Glue {
            get {
                return this.GlueField;
            }
            set {
                if ((this.GlueField.Equals(value) != true)) {
                    this.GlueField = value;
                    this.RaisePropertyChanged("Glue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((this.GradeField.Equals(value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Thickness {
            get {
                return this.ThicknessField;
            }
            set {
                if ((this.ThicknessField.Equals(value) != true)) {
                    this.ThicknessField = value;
                    this.RaisePropertyChanged("Thickness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Stuff Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeId {
            get {
                return this.TypeIdField;
            }
            set {
                if ((this.TypeIdField.Equals(value) != true)) {
                    this.TypeIdField = value;
                    this.RaisePropertyChanged("TypeId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StockPofak", Namespace="http://schemas.datacontract.org/2004/07/SharedLib")]
    [System.SerializableAttribute()]
    public partial class StockPofak : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Pofak PofakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PofakIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ReserveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Pofak Pofak {
            get {
                return this.PofakField;
            }
            set {
                if ((object.ReferenceEquals(this.PofakField, value) != true)) {
                    this.PofakField = value;
                    this.RaisePropertyChanged("Pofak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PofakId {
            get {
                return this.PofakIdField;
            }
            set {
                if ((this.PofakIdField.Equals(value) != true)) {
                    this.PofakIdField = value;
                    this.RaisePropertyChanged("PofakId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Reserve {
            get {
                return this.ReserveField;
            }
            set {
                if ((this.ReserveField.Equals(value) != true)) {
                    this.ReserveField = value;
                    this.RaisePropertyChanged("Reserve");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LaminetOperation", Namespace="http://schemas.datacontract.org/2004/07/SharedLib")]
    [System.SerializableAttribute()]
    public partial class LaminetOperation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Taqeh AstarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AstarIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Users ConfirmerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConfirmerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Taqeh CreatedTaqehField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatedTaqehIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetLaminetTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetOrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetReceiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetSentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Pofak PofakField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PofakIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ReceiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReceivedQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Users ReceiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReceiverIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> SendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Users SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShortageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Taqeh TaqehField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaqehIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Users UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Taqeh Astar {
            get {
                return this.AstarField;
            }
            set {
                if ((object.ReferenceEquals(this.AstarField, value) != true)) {
                    this.AstarField = value;
                    this.RaisePropertyChanged("Astar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AstarId {
            get {
                return this.AstarIdField;
            }
            set {
                if ((this.AstarIdField.Equals(value) != true)) {
                    this.AstarIdField = value;
                    this.RaisePropertyChanged("AstarId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Users Confirmer {
            get {
                return this.ConfirmerField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfirmerField, value) != true)) {
                    this.ConfirmerField = value;
                    this.RaisePropertyChanged("Confirmer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConfirmerId {
            get {
                return this.ConfirmerIdField;
            }
            set {
                if ((this.ConfirmerIdField.Equals(value) != true)) {
                    this.ConfirmerIdField = value;
                    this.RaisePropertyChanged("ConfirmerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Taqeh CreatedTaqeh {
            get {
                return this.CreatedTaqehField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedTaqehField, value) != true)) {
                    this.CreatedTaqehField = value;
                    this.RaisePropertyChanged("CreatedTaqeh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatedTaqehId {
            get {
                return this.CreatedTaqehIdField;
            }
            set {
                if ((this.CreatedTaqehIdField.Equals(value) != true)) {
                    this.CreatedTaqehIdField = value;
                    this.RaisePropertyChanged("CreatedTaqehId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetLaminetType {
            get {
                return this.GetLaminetTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.GetLaminetTypeField, value) != true)) {
                    this.GetLaminetTypeField = value;
                    this.RaisePropertyChanged("GetLaminetType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetOrderDate {
            get {
                return this.GetOrderDateField;
            }
            set {
                if ((object.ReferenceEquals(this.GetOrderDateField, value) != true)) {
                    this.GetOrderDateField = value;
                    this.RaisePropertyChanged("GetOrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetReceiveDate {
            get {
                return this.GetReceiveDateField;
            }
            set {
                if ((object.ReferenceEquals(this.GetReceiveDateField, value) != true)) {
                    this.GetReceiveDateField = value;
                    this.RaisePropertyChanged("GetReceiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetSentDate {
            get {
                return this.GetSentDateField;
            }
            set {
                if ((object.ReferenceEquals(this.GetSentDateField, value) != true)) {
                    this.GetSentDateField = value;
                    this.RaisePropertyChanged("GetSentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetStatus {
            get {
                return this.GetStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.GetStatusField, value) != true)) {
                    this.GetStatusField = value;
                    this.RaisePropertyChanged("GetStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Pofak Pofak {
            get {
                return this.PofakField;
            }
            set {
                if ((object.ReferenceEquals(this.PofakField, value) != true)) {
                    this.PofakField = value;
                    this.RaisePropertyChanged("Pofak");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PofakId {
            get {
                return this.PofakIdField;
            }
            set {
                if ((this.PofakIdField.Equals(value) != true)) {
                    this.PofakIdField = value;
                    this.RaisePropertyChanged("PofakId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ReceiveDate {
            get {
                return this.ReceiveDateField;
            }
            set {
                if ((this.ReceiveDateField.Equals(value) != true)) {
                    this.ReceiveDateField = value;
                    this.RaisePropertyChanged("ReceiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceivedQuantity {
            get {
                return this.ReceivedQuantityField;
            }
            set {
                if ((this.ReceivedQuantityField.Equals(value) != true)) {
                    this.ReceivedQuantityField = value;
                    this.RaisePropertyChanged("ReceivedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Users Receiver {
            get {
                return this.ReceiverField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverField, value) != true)) {
                    this.ReceiverField = value;
                    this.RaisePropertyChanged("Receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReceiverId {
            get {
                return this.ReceiverIdField;
            }
            set {
                if ((this.ReceiverIdField.Equals(value) != true)) {
                    this.ReceiverIdField = value;
                    this.RaisePropertyChanged("ReceiverId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((this.SendDateField.Equals(value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Users Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SenderId {
            get {
                return this.SenderIdField;
            }
            set {
                if ((this.SenderIdField.Equals(value) != true)) {
                    this.SenderIdField = value;
                    this.RaisePropertyChanged("SenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Shortage {
            get {
                return this.ShortageField;
            }
            set {
                if ((this.ShortageField.Equals(value) != true)) {
                    this.ShortageField = value;
                    this.RaisePropertyChanged("Shortage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Taqeh Taqeh {
            get {
                return this.TaqehField;
            }
            set {
                if ((object.ReferenceEquals(this.TaqehField, value) != true)) {
                    this.TaqehField = value;
                    this.RaisePropertyChanged("Taqeh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaqehId {
            get {
                return this.TaqehIdField;
            }
            set {
                if ((this.TaqehIdField.Equals(value) != true)) {
                    this.TaqehIdField = value;
                    this.RaisePropertyChanged("TaqehId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Users User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/SharedLib")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> HireDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SharedService.TaqehService.Stuff RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((this.BirthDateField.Equals(value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> HireDate {
            get {
                return this.HireDateField;
            }
            set {
                if ((this.HireDateField.Equals(value) != true)) {
                    this.HireDateField = value;
                    this.RaisePropertyChanged("HireDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SharedService.TaqehService.Stuff Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TaqehService.ITaqehService")]
    public interface ITaqehService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehStockService/GetStockList", ReplyAction="http://tempuri.org/ITaqehStockService/GetStockListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedService.TaqehService.DapperException), Action="http://tempuri.org/ITaqehStockService/GetStockListDapperExceptionFault", Name="DapperException", Namespace="http://schemas.datacontract.org/2004/07/SahraShoesService.Exceptions")]
        SharedService.TaqehService.StockTaqeh[] GetStockList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehStockService/GetStockList", ReplyAction="http://tempuri.org/ITaqehStockService/GetStockListResponse")]
        System.Threading.Tasks.Task<SharedService.TaqehService.StockTaqeh[]> GetStockListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehStockService/GetSimpleStockList", ReplyAction="http://tempuri.org/ITaqehStockService/GetSimpleStockListResponse")]
        SharedService.TaqehService.StockTaqeh[] GetSimpleStockList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehStockService/GetSimpleStockList", ReplyAction="http://tempuri.org/ITaqehStockService/GetSimpleStockListResponse")]
        System.Threading.Tasks.Task<SharedService.TaqehService.StockTaqeh[]> GetSimpleStockListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehStockService/insertStock", ReplyAction="http://tempuri.org/ITaqehStockService/insertStockResponse")]
        int insertStock(SharedService.TaqehService.StockTaqeh item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehStockService/insertStock", ReplyAction="http://tempuri.org/ITaqehStockService/insertStockResponse")]
        System.Threading.Tasks.Task<int> insertStockAsync(SharedService.TaqehService.StockTaqeh item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehStockService/updateStock", ReplyAction="http://tempuri.org/ITaqehStockService/updateStockResponse")]
        bool updateStock(SharedService.TaqehService.StockTaqeh item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehStockService/updateStock", ReplyAction="http://tempuri.org/ITaqehStockService/updateStockResponse")]
        System.Threading.Tasks.Task<bool> updateStockAsync(SharedService.TaqehService.StockTaqeh item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPofakService/GetPofakList", ReplyAction="http://tempuri.org/IPofakService/GetPofakListResponse")]
        SharedService.TaqehService.Pofak[] GetPofakList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPofakService/GetPofakList", ReplyAction="http://tempuri.org/IPofakService/GetPofakListResponse")]
        System.Threading.Tasks.Task<SharedService.TaqehService.Pofak[]> GetPofakListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPofakService/GetSimpleStockPofak", ReplyAction="http://tempuri.org/IPofakService/GetSimpleStockPofakResponse")]
        SharedService.TaqehService.StockPofak[] GetSimpleStockPofak();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPofakService/GetSimpleStockPofak", ReplyAction="http://tempuri.org/IPofakService/GetSimpleStockPofakResponse")]
        System.Threading.Tasks.Task<SharedService.TaqehService.StockPofak[]> GetSimpleStockPofakAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPofakService/updateStockPofak", ReplyAction="http://tempuri.org/IPofakService/updateStockPofakResponse")]
        bool updateStockPofak(SharedService.TaqehService.StockPofak sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPofakService/updateStockPofak", ReplyAction="http://tempuri.org/IPofakService/updateStockPofakResponse")]
        System.Threading.Tasks.Task<bool> updateStockPofakAsync(SharedService.TaqehService.StockPofak sp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPofakService/getPofakStockList", ReplyAction="http://tempuri.org/IPofakService/getPofakStockListResponse")]
        SharedService.TaqehService.StockPofak[] getPofakStockList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPofakService/getPofakStockList", ReplyAction="http://tempuri.org/IPofakService/getPofakStockListResponse")]
        System.Threading.Tasks.Task<SharedService.TaqehService.StockPofak[]> getPofakStockListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPofakService/insertPofak", ReplyAction="http://tempuri.org/IPofakService/insertPofakResponse")]
        int insertPofak(SharedService.TaqehService.Pofak p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPofakService/insertPofak", ReplyAction="http://tempuri.org/IPofakService/insertPofakResponse")]
        System.Threading.Tasks.Task<int> insertPofakAsync(SharedService.TaqehService.Pofak p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/GetSimpleList", ReplyAction="http://tempuri.org/ITaqehService/GetSimpleListResponse")]
        SharedService.TaqehService.Taqeh[] GetSimpleList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/GetSimpleList", ReplyAction="http://tempuri.org/ITaqehService/GetSimpleListResponse")]
        System.Threading.Tasks.Task<SharedService.TaqehService.Taqeh[]> GetSimpleListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/GetDetailedList", ReplyAction="http://tempuri.org/ITaqehService/GetDetailedListResponse")]
        SharedService.TaqehService.Taqeh[] GetDetailedList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/GetDetailedList", ReplyAction="http://tempuri.org/ITaqehService/GetDetailedListResponse")]
        System.Threading.Tasks.Task<SharedService.TaqehService.Taqeh[]> GetDetailedListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/insertTaqeh", ReplyAction="http://tempuri.org/ITaqehService/insertTaqehResponse")]
        int insertTaqeh(SharedService.TaqehService.Taqeh t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/insertTaqeh", ReplyAction="http://tempuri.org/ITaqehService/insertTaqehResponse")]
        System.Threading.Tasks.Task<int> insertTaqehAsync(SharedService.TaqehService.Taqeh t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/GetLaminetList", ReplyAction="http://tempuri.org/ITaqehService/GetLaminetListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SharedService.TaqehService.DapperException), Action="http://tempuri.org/ITaqehService/GetLaminetListDapperExceptionFault", Name="DapperException", Namespace="http://schemas.datacontract.org/2004/07/SahraShoesService.Exceptions")]
        SharedService.TaqehService.LaminetOperation[] GetLaminetList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/GetLaminetList", ReplyAction="http://tempuri.org/ITaqehService/GetLaminetListResponse")]
        System.Threading.Tasks.Task<SharedService.TaqehService.LaminetOperation[]> GetLaminetListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/updateLaminet", ReplyAction="http://tempuri.org/ITaqehService/updateLaminetResponse")]
        bool updateLaminet(SharedService.TaqehService.LaminetOperation lo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/updateLaminet", ReplyAction="http://tempuri.org/ITaqehService/updateLaminetResponse")]
        System.Threading.Tasks.Task<bool> updateLaminetAsync(SharedService.TaqehService.LaminetOperation lo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/GetLaminetSimpleList", ReplyAction="http://tempuri.org/ITaqehService/GetLaminetSimpleListResponse")]
        SharedService.TaqehService.LaminetOperation[] GetLaminetSimpleList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/GetLaminetSimpleList", ReplyAction="http://tempuri.org/ITaqehService/GetLaminetSimpleListResponse")]
        System.Threading.Tasks.Task<SharedService.TaqehService.LaminetOperation[]> GetLaminetSimpleListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/insertLaminet", ReplyAction="http://tempuri.org/ITaqehService/insertLaminetResponse")]
        int insertLaminet(SharedService.TaqehService.LaminetOperation lo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/insertLaminet", ReplyAction="http://tempuri.org/ITaqehService/insertLaminetResponse")]
        System.Threading.Tasks.Task<int> insertLaminetAsync(SharedService.TaqehService.LaminetOperation lo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/updateTaqeh", ReplyAction="http://tempuri.org/ITaqehService/updateTaqehResponse")]
        bool updateTaqeh(SharedService.TaqehService.Taqeh t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaqehService/updateTaqeh", ReplyAction="http://tempuri.org/ITaqehService/updateTaqehResponse")]
        System.Threading.Tasks.Task<bool> updateTaqehAsync(SharedService.TaqehService.Taqeh t);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaqehServiceChannel : SharedService.TaqehService.ITaqehService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaqehServiceClient : System.ServiceModel.ClientBase<SharedService.TaqehService.ITaqehService>, SharedService.TaqehService.ITaqehService {
        
        public TaqehServiceClient() {
        }
        
        public TaqehServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaqehServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaqehServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaqehServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SharedService.TaqehService.StockTaqeh[] GetStockList() {
            return base.Channel.GetStockList();
        }
        
        public System.Threading.Tasks.Task<SharedService.TaqehService.StockTaqeh[]> GetStockListAsync() {
            return base.Channel.GetStockListAsync();
        }
        
        public SharedService.TaqehService.StockTaqeh[] GetSimpleStockList() {
            return base.Channel.GetSimpleStockList();
        }
        
        public System.Threading.Tasks.Task<SharedService.TaqehService.StockTaqeh[]> GetSimpleStockListAsync() {
            return base.Channel.GetSimpleStockListAsync();
        }
        
        public int insertStock(SharedService.TaqehService.StockTaqeh item) {
            return base.Channel.insertStock(item);
        }
        
        public System.Threading.Tasks.Task<int> insertStockAsync(SharedService.TaqehService.StockTaqeh item) {
            return base.Channel.insertStockAsync(item);
        }
        
        public bool updateStock(SharedService.TaqehService.StockTaqeh item) {
            return base.Channel.updateStock(item);
        }
        
        public System.Threading.Tasks.Task<bool> updateStockAsync(SharedService.TaqehService.StockTaqeh item) {
            return base.Channel.updateStockAsync(item);
        }
        
        public SharedService.TaqehService.Pofak[] GetPofakList() {
            return base.Channel.GetPofakList();
        }
        
        public System.Threading.Tasks.Task<SharedService.TaqehService.Pofak[]> GetPofakListAsync() {
            return base.Channel.GetPofakListAsync();
        }
        
        public SharedService.TaqehService.StockPofak[] GetSimpleStockPofak() {
            return base.Channel.GetSimpleStockPofak();
        }
        
        public System.Threading.Tasks.Task<SharedService.TaqehService.StockPofak[]> GetSimpleStockPofakAsync() {
            return base.Channel.GetSimpleStockPofakAsync();
        }
        
        public bool updateStockPofak(SharedService.TaqehService.StockPofak sp) {
            return base.Channel.updateStockPofak(sp);
        }
        
        public System.Threading.Tasks.Task<bool> updateStockPofakAsync(SharedService.TaqehService.StockPofak sp) {
            return base.Channel.updateStockPofakAsync(sp);
        }
        
        public SharedService.TaqehService.StockPofak[] getPofakStockList() {
            return base.Channel.getPofakStockList();
        }
        
        public System.Threading.Tasks.Task<SharedService.TaqehService.StockPofak[]> getPofakStockListAsync() {
            return base.Channel.getPofakStockListAsync();
        }
        
        public int insertPofak(SharedService.TaqehService.Pofak p) {
            return base.Channel.insertPofak(p);
        }
        
        public System.Threading.Tasks.Task<int> insertPofakAsync(SharedService.TaqehService.Pofak p) {
            return base.Channel.insertPofakAsync(p);
        }
        
        public SharedService.TaqehService.Taqeh[] GetSimpleList() {
            return base.Channel.GetSimpleList();
        }
        
        public System.Threading.Tasks.Task<SharedService.TaqehService.Taqeh[]> GetSimpleListAsync() {
            return base.Channel.GetSimpleListAsync();
        }
        
        public SharedService.TaqehService.Taqeh[] GetDetailedList() {
            return base.Channel.GetDetailedList();
        }
        
        public System.Threading.Tasks.Task<SharedService.TaqehService.Taqeh[]> GetDetailedListAsync() {
            return base.Channel.GetDetailedListAsync();
        }
        
        public int insertTaqeh(SharedService.TaqehService.Taqeh t) {
            return base.Channel.insertTaqeh(t);
        }
        
        public System.Threading.Tasks.Task<int> insertTaqehAsync(SharedService.TaqehService.Taqeh t) {
            return base.Channel.insertTaqehAsync(t);
        }
        
        public SharedService.TaqehService.LaminetOperation[] GetLaminetList() {
            return base.Channel.GetLaminetList();
        }
        
        public System.Threading.Tasks.Task<SharedService.TaqehService.LaminetOperation[]> GetLaminetListAsync() {
            return base.Channel.GetLaminetListAsync();
        }
        
        public bool updateLaminet(SharedService.TaqehService.LaminetOperation lo) {
            return base.Channel.updateLaminet(lo);
        }
        
        public System.Threading.Tasks.Task<bool> updateLaminetAsync(SharedService.TaqehService.LaminetOperation lo) {
            return base.Channel.updateLaminetAsync(lo);
        }
        
        public SharedService.TaqehService.LaminetOperation[] GetLaminetSimpleList() {
            return base.Channel.GetLaminetSimpleList();
        }
        
        public System.Threading.Tasks.Task<SharedService.TaqehService.LaminetOperation[]> GetLaminetSimpleListAsync() {
            return base.Channel.GetLaminetSimpleListAsync();
        }
        
        public int insertLaminet(SharedService.TaqehService.LaminetOperation lo) {
            return base.Channel.insertLaminet(lo);
        }
        
        public System.Threading.Tasks.Task<int> insertLaminetAsync(SharedService.TaqehService.LaminetOperation lo) {
            return base.Channel.insertLaminetAsync(lo);
        }
        
        public bool updateTaqeh(SharedService.TaqehService.Taqeh t) {
            return base.Channel.updateTaqeh(t);
        }
        
        public System.Threading.Tasks.Task<bool> updateTaqehAsync(SharedService.TaqehService.Taqeh t) {
            return base.Channel.updateTaqehAsync(t);
        }
    }
}
